// <auto-generated />
using System;
using Mediary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mediary.Migrations
{
    [DbContext(typeof(MessageContext))]
    [Migration("20220624025635_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("Mediary.MissedMessages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Dup")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Payload")
                        .HasColumnType("BLOB");

                    b.Property<int?>("QualityOfServiceLevel")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Retain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MissedMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
